name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v3

  build:
    name: Go Build & Coverage
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./cmd/*

    - name: Unit test
      run: go test -v ./...

    - name: Coverage test
      run: go test -covermode=count -coverprofile=coverage.txt ./...

    - uses: codecov/codecov-action@v3
      with:
        files: ./coverage.txt
        fail_ci_if_error: true
        verbose: true
